### ISSUE TITLE
PostgreSQL 17 support

### ISSUE THREAD

**Issue by devrimgunduz** [EnterpriseDB/pg_failover_slots#44]
Hi,

1.0.1 fails to build against PostgreSQL 17. Log is below. v17beta2 is already out. Can you please take a look? 

Thanks, Devrim

> /usr/bin/clang -Wno-ignored-attributes -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-unused-command-line-argument -Wno-compound-token-split-by-macro -Wno-format-truncation -O2  -I /usr/pgsql-17/include -I. -I./ -I/usr/pgsql-17/include/server -I/usr/pgsql-17/include/internal  -D_GNU_SOURCE -I/usr/include/libxml2 -DWITH_GZFILEOP  -I/usr/include -flto=thin -emit-llvm -c -o pg_failover_slots.bc pg_failover_slots.c
pg_failover_slots.c:103:7: error: redefinition of 'standby_slot_names' with a different type: 'List *' (aka 'struct List *') vs 'char *'
  103 | List *standby_slot_names = NIL;
      |       ^
/usr/pgsql-17/include/server/replication/slot.h:232:26: note: previous declaration is here
  232 | extern PGDLLIMPORT char *standby_slot_names;
      |                          ^
pg_failover_slots.c:238:13: warning: incompatible pointer types passing 'char *' to parameter of type 'List *' (aka 'struct List *') [-Wincompatible-pointer-types]
  238 |                 list_free(standby_slot_names);
      |                           ^~~~~~~~~~~~~~~~~~
/usr/pgsql-17/include/server/nodes/pg_list.h:672:29: note: passing argument to parameter 'list' here
  672 | extern void list_free(List *list);
      |                             ^
pg_failover_slots.c:249:10: warning: incompatible pointer types passing 'char **' to parameter of type 'List **' (aka 'struct List **') [-Wincompatible-pointer-types]
  249 |                                                                  &standby_slot_names);
      |                                                                  ^~~~~~~~~~~~~~~~~~~
/usr/pgsql-17/include/server/utils/varlena.h:31:18: note: passing argument to parameter 'namelist' here
   31 |                                                                   List **namelist);
      |                                                                          ^
pg_failover_slots.c:768:32: error: too few arguments to function call, expected 6, have 4
  767 |                 ReplicationSlotCreate(remote_slot->name, true, RS_EPHEMERAL,
      |                 ~~~~~~~~~~~~~~~~~~~~~
  768 |                                                           remote_slot->two_phase);
      |                                                                                 ^
/usr/pgsql-17/include/server/replication/slot.h:239:13: note: 'ReplicationSlotCreate' declared here
  239 | extern void ReplicationSlotCreate(const char *name, bool db_specific,
      |             ^                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  240 |                                                                   ReplicationSlotPersistency persistency,
      |                                                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  241 |                                                                   bool two_phase, bool failover,
      |                                                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  242 |                                                                   bool synced);
      |                                                                   ~~~~~~~~~~~
pg_failover_slots.c:1137:25: warning: comparison of distinct pointer types ('char *' and 'List *' (aka 'struct List *')) [-Wcompare-distinct-pointer-types]
 1137 |         if (standby_slot_names != cached_standby_slot_names)
      |             ~~~~~~~~~~~~~~~~~~ ^  ~~~~~~~~~~~~~~~~~~~~~~~~~
pg_failover_slots.c:1141:24: warning: incompatible pointer types passing 'char *' to parameter of type 'List *' (aka 'struct List *') [-Wincompatible-pointer-types]
 1141 |                         if (list_member_str(standby_slot_names,
      |                                             ^~~~~~~~~~~~~~~~~~
pg_failover_slots.c:1119:23: note: passing argument to parameter 'l' here
 1119 | list_member_str(List *l, const char *str)
      |                       ^
pg_failover_slots.c:1151:29: warning: incompatible pointer types assigning to 'List *' (aka 'struct List *') from 'char *' [-Wincompatible-pointer-types]
 1151 |                 cached_standby_slot_names = standby_slot_names;
      |                                           ^ ~~~~~~~~~~~~~~~~~~
pg_failover_slots.c:1161:15: warning: incompatible pointer types passing 'char *' to parameter of type 'const List *' (aka 'const struct List *') [-Wincompatible-pointer-types]
 1161 |                 list_length(standby_slot_names) == 0)
      |                             ^~~~~~~~~~~~~~~~~~
/usr/pgsql-17/include/server/nodes/pg_list.h:152:25: note: passing argument to parameter 'l' here
  152 | list_length(const List *l)
      |                         ^
pg_failover_slots.c:1198:39: warning: incompatible pointer types passing 'char *' to parameter of type 'const List *' (aka 'const struct List *') [-Wincompatible-pointer-types]
 1198 |                         wait_slots_remaining = list_length(standby_slot_names);
      |                                                            ^~~~~~~~~~~~~~~~~~
/usr/pgsql-17/include/server/nodes/pg_list.h:152:25: note: passing argument to parameter 'l' here
  152 | list_length(const List *l)
      |                         ^
pg_failover_slots.c:1208:25: warning: incompatible pointer types passing 'char *' to parameter of type 'const List *' (aka 'const struct List *') [-Wincompatible-pointer-types]
 1208 |                                                                            list_length(standby_slot_names));
      |                                                                                        ^~~~~~~~~~~~~~~~~~
/usr/pgsql-17/include/server/c.h:1004:28: note: expanded from macro 'Min'
 1004 | #define Min(x, y)               ((x) < (y) ? (x) : (y))
      |                                         ^
/usr/pgsql-17/include/server/nodes/pg_list.h:152:25: note: passing argument to parameter 'l' here
  152 | list_length(const List *l)
      |                         ^
pg_failover_slots.c:1208:25: warning: incompatible pointer types passing 'char *' to parameter of type 'const List *' (aka 'const struct List *') [-Wincompatible-pointer-types]
 1208 |                                                                            list_length(standby_slot_names));
      |                                                                                        ^~~~~~~~~~~~~~~~~~
/usr/pgsql-17/include/server/c.h:1004:40: note: expanded from macro 'Min'
 1004 | #define Min(x, y)               ((x) < (y) ? (x) : (y))
      |                                                     ^
/usr/pgsql-17/include/server/nodes/pg_list.h:152:25: note: passing argument to parameter 'l' here
  152 | list_length(const List *l)
      |                         ^
pg_failover_slots.c:1212:43: warning: incompatible pointer types passing 'char *' to parameter of type 'const List *' (aka 'const struct List *') [-Wincompatible-pointer-types]
 1212 |                            wait_slots_remaining <= list_length(standby_slot_names));
      |                                                                ^~~~~~~~~~~~~~~~~~
/usr/pgsql-17/include/server/c.h:875:9: note: expanded from macro 'Assert'
  875 |                 if (!(condition)) \
      |                       ^~~~~~~~~
/usr/pgsql-17/include/server/nodes/pg_list.h:152:25: note: passing argument to parameter 'l' here
  152 | list_length(const List *l)
      |                         ^
pg_failover_slots.c:1222:25: warning: incompatible pointer types passing 'char *' to parameter of type 'List *' (aka 'struct List *') [-Wincompatible-pointer-types]
 1222 |                         if (!list_member_str(standby_slot_names, NameStr(s->data.name)))
      |                                              ^~~~~~~~~~~~~~~~~~
pg_failover_slots.c:1119:23: note: passing argument to parameter 'l' here
 1119 | list_member_str(List *l, const char *str)
      |                       ^
11 warnings and 2 errors generated.
make[1]: *** [/usr/pgsql-17/lib/pgxs/src/makefiles/../../src/Makefile.global:1085: pg_failover_slots.bc] Error 1
make[1]: *** Waiting for unfinished jobs....
pg_failover_slots.c:103:7: error: conflicting types for ‘standby_slot_names’; have ‘List *’
  103 | List *standby_slot_names = NIL;
      |       ^~~~~~~~~~~~~~~~~~
In file included from /usr/pgsql-17/include/server/replication/logical.h:15,
                 from /usr/pgsql-17/include/server/replication/decode.h:14,
                 from pg_failover_slots.c:38:
/usr/pgsql-17/include/server/replication/slot.h:232:26: note: previous declaration of ‘standby_slot_names’ with type ‘char *’
  232 | extern PGDLLIMPORT char *standby_slot_names;
      |                          ^~~~~~~~~~~~~~~~~~
pg_failover_slots.c: In function ‘synchronize_one_slot’:
pg_failover_slots.c:767:17: error: too few arguments to function ‘ReplicationSlotCreate’
  767 |                 ReplicationSlotCreate(remote_slot->name, true, RS_EPHEMERAL,
      |                 ^~~~~~~~~~~~~~~~~~~~~
/usr/pgsql-17/include/server/replication/slot.h:239:13: note: declared here
  239 | extern void ReplicationSlotCreate(const char *name, bool db_specific,
      |             ^~~~~~~~~~~~~~~~~~~~~
make[1]: *** [<builtin>: pg_failover_slots.o] Error 1

**Comment by devrimgunduz** [comment]
Hi @PJMODOS ,

We need a new release for building the RPMs. Can you please push a new one?

Thanks!

Regards, Devrim

**Comment by devrimgunduz** [comment]
Hi,

I noticed 1.1.0 tag but it fails to build against v17 beta3:

`make[1]: *** [/usr/pgsql-17/lib/pgxs/src/makefiles/../../src/Makefile.global:1085: pg_failover_slots.bc] Error 1
make[1]: *** Waiting for unfinished jobs....
pg_failover_slots.c:102:7: error: conflicting types for ‘standby_slot_names’; have ‘List *’
  102 | List *standby_slot_names = NIL;
      |       ^~~~~~~~~~~~~~~~~~
In file included from /usr/pgsql-17/include/server/replication/logical.h:15,
                 from /usr/pgsql-17/include/server/replication/decode.h:14,
                 from pg_failover_slots.c:38:
/usr/pgsql-17/include/server/replication/slot.h:232:26: note: previous declaration of ‘standby_slot_names’ with type ‘char *’
  232 | extern PGDLLIMPORT char *standby_slot_names;
      |                          ^~~~~~~~~~~~~~~~~~
make[1]: *** [<builtin>: pg_failover_slots.o] Error 1

**Comment by devrimgunduz** [comment]
FWIW there are a lot of build warnings as well. This is GCC 14.1 on Fedora 40:

`/usr/bin/clang -Wno-ignored-attributes -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-unused-command-line-argument -Wno-compound-token-split-by-macro -Wno-format-truncation -O2  -I /usr/pgsql-17/include -I. -I./ -I/usr/pgsql-17/include/server -I/usr/pgsql-17/include/internal  -D_GNU_SOURCE -I/usr/include/libxml2 -DWITH_GZFILEOP  -I/usr/include -flto=thin -emit-llvm -c -o pg_failover_slots.bc pg_failover_slots.c
pg_failover_slots.c:102:7: error: redefinition of 'standby_slot_names' with a different type: 'List *' (aka 'struct List *') vs 'char *'
  102 | List *standby_slot_names = NIL;
      |       ^
/usr/pgsql-17/include/server/replication/slot.h:232:26: note: previous declaration is here
  232 | extern PGDLLIMPORT char *standby_slot_names;
      |                          ^
pg_failover_slots.c:241:13: warning: incompatible pointer types passing 'char *' to parameter of type 'List *' (aka 'struct List *') [-Wincompatible-pointer-types]
  241 |                 list_free(standby_slot_names);
      |                           ^~~~~~~~~~~~~~~~~~
/usr/pgsql-17/include/server/nodes/pg_list.h:672:29: note: passing argument to parameter 'list' here
  672 | extern void list_free(List *list);
      |                             ^
pg_failover_slots.c:252:10: warning: incompatible pointer types passing 'char **' to parameter of type 'List **' (aka 'struct List **') [-Wincompatible-pointer-types]
  252 |                                                                  &standby_slot_names);
      |                                                                  ^~~~~~~~~~~~~~~~~~~
/usr/pgsql-17/include/server/utils/varlena.h:31:18: note: passing argument to parameter 'namelist' here
   31 |                                                                   List **namelist);
      |                                                                          ^
pg_failover_slots.c:1145:25: warning: comparison of distinct pointer types ('char *' and 'List *' (aka 'struct List *')) [-Wcompare-distinct-pointer-types]
 1145 |         if (standby_slot_names != cached_standby_slot_names)
      |             ~~~~~~~~~~~~~~~~~~ ^  ~~~~~~~~~~~~~~~~~~~~~~~~~
pg_failover_slots.c:1149:24: warning: incompatible pointer types passing 'char *' to parameter of type 'List *' (aka 'struct List *') [-Wincompatible-pointer-types]
 1149 |                         if (list_member_str(standby_slot_names,
      |                                             ^~~~~~~~~~~~~~~~~~
pg_failover_slots.c:1127:23: note: passing argument to parameter 'l' here
 1127 | list_member_str(List *l, const char *str)
      |                       ^
pg_failover_slots.c:1159:29: warning: incompatible pointer types assigning to 'List *' (aka 'struct List *') from 'char *' [-Wincompatible-pointer-types]
 1159 |                 cached_standby_slot_names = standby_slot_names;
      |                                           ^ ~~~~~~~~~~~~~~~~~~
pg_failover_slots.c:1169:15: warning: incompatible pointer types passing 'char *' to parameter of type 'const List *' (aka 'const struct List *') [-Wincompatible-pointer-types]
 1169 |                 list_length(standby_slot_names) == 0)
      |                             ^~~~~~~~~~~~~~~~~~
/usr/pgsql-17/include/server/nodes/pg_list.h:152:25: note: passing argument to parameter 'l' here
  152 | list_length(const List *l)
      |                         ^
pg_failover_slots.c:1206:39: warning: incompatible pointer types passing 'char *' to parameter of type 'const List *' (aka 'const struct List *') [-Wincompatible-pointer-types]
 1206 |                         wait_slots_remaining = list_length(standby_slot_names);
      |                                                            ^~~~~~~~~~~~~~~~~~
/usr/pgsql-17/include/server/nodes/pg_list.h:152:25: note: passing argument to parameter 'l' here
  152 | list_length(const List *l)
      |                         ^
pg_failover_slots.c:1216:25: warning: incompatible pointer types passing 'char *' to parameter of type 'const List *' (aka 'const struct List *') [-Wincompatible-pointer-types]
 1216 |                                                                            list_length(standby_slot_names));
      |                                                                                        ^~~~~~~~~~~~~~~~~~
/usr/pgsql-17/include/server/c.h:1004:28: note: expanded from macro 'Min'
 1004 | #define Min(x, y)               ((x) < (y) ? (x) : (y))
      |                                         ^
/usr/pgsql-17/include/server/nodes/pg_list.h:152:25: note: passing argument to parameter 'l' here
  152 | list_length(const List *l)
      |                         ^
pg_failover_slots.c:1216:25: warning: incompatible pointer types passing 'char *' to parameter of type 'const List *' (aka 'const struct List *') [-Wincompatible-pointer-types]
 1216 |                                                                            list_length(standby_slot_names));
      |                                                                                        ^~~~~~~~~~~~~~~~~~
/usr/pgsql-17/include/server/c.h:1004:40: note: expanded from macro 'Min'
 1004 | #define Min(x, y)               ((x) < (y) ? (x) : (y))
      |                                                     ^
/usr/pgsql-17/include/server/nodes/pg_list.h:152:25: note: passing argument to parameter 'l' here
  152 | list_length(const List *l)
      |                         ^
pg_failover_slots.c:1220:43: warning: incompatible pointer types passing 'char *' to parameter of type 'const List *' (aka 'const struct List *') [-Wincompatible-pointer-types]
 1220 |                            wait_slots_remaining <= list_length(standby_slot_names));
      |                                                                ^~~~~~~~~~~~~~~~~~
/usr/pgsql-17/include/server/c.h:875:9: note: expanded from macro 'Assert'
  875 |                 if (!(condition)) \
      |                       ^~~~~~~~~
/usr/pgsql-17/include/server/nodes/pg_list.h:152:25: note: passing argument to parameter 'l' here
  152 | list_length(const List *l)
      |                         ^
pg_failover_slots.c:1230:25: warning: incompatible pointer types passing 'char *' to parameter of type 'List *' (aka 'struct List *') [-Wincompatible-pointer-types]
 1230 |                         if (!list_member_str(standby_slot_names, NameStr(s->data.name)))
      |                                              ^~~~~~~~~~~~~~~~~~
pg_failover_slots.c:1127:23: note: passing argument to parameter 'l' here
 1127 | list_member_str(List *l, const char *str)
      |                       ^
11 warnings and 1 error generated.
make[1]: *** [/usr/pgsql-17/lib/pgxs/src/makefiles/../../src/Makefile.global:1085: pg_failover_slots.bc] Error 1
make[1]: *** Waiting for unfinished jobs....
pg_failover_slots.c:102:7: error: conflicting types for ‘standby_slot_names’; have ‘List *’
  102 | List *standby_slot_names = NIL;
      |       ^~~~~~~~~~~~~~~~~~
In file included from /usr/pgsql-17/include/server/replication/logical.h:15,
                 from /usr/pgsql-17/include/server/replication/decode.h:14,
                 from pg_failover_slots.c:38:
/usr/pgsql-17/include/server/replication/slot.h:232:26: note: previous declaration of ‘standby_slot_names’ with type ‘char *’
  232 | extern PGDLLIMPORT char *standby_slot_names;
      |                          ^~~~~~~~~~~~~~~~~~
make[1]: *** [<builtin>: pg_failover_slots.o] Error 1
`

**Comment by devrimgunduz** [comment]
Also I would really appreciate if you do a release rather than a tag. Also adding changelog to the release would be great, like this one:

https://github.com/EnterpriseDB/pg_failover_slots/commit/e26870be3b8c6b4cdd94d255a012a46dbd04a29a

**Comment by devrimgunduz** [comment]
@petere so I think this is what got me confused in #48 . 1.1.0 fails to build against PG17 beta3 as well with the same errors on Fedora 40 and RHEL 9 (GCC 14 and GCC 11 respectively). It builds fine on RHEL 8 (GCC 8.5.0)

**Comment by devrimgunduz** [comment]
1.1.0 fixes these issues. Thanks!
